### ISSUE TITLE
No 'EMA_records_tire.mat'

### ISSUE THREAD

**Issue by ljh553128775** [KIT-FAST/modalAnalysis-OMA-EMA#1]
I want to know the format your measurement data was stored.
vector? matrix? cell? Can you give a simple example of measured data?

**Comment by awiawi** [comment]
For EMA the expected data is a matrix `FRF` with the frequencies in the 1st dimension and the sensors in the 2nd dimension, so each column represents a sensor. Moreover, a column vector `frequencyBand` with the corresponding frequencies is expected.

`size(FRF) = n_frequencies, n_sensors`
`size(frequencyBand) = n_frequencies`

![ema_trim](https://user-images.githubusercontent.com/13416487/86216540-7b78a900-bb7e-11ea-9b8d-5858e035ef32.png)

For OMA with a single measurement, a matrix `records` with the time in the 1st dimension and the sensors in the 2nd dimension is expected, so each column represents a sensor.

`size(records) = n_time, n_sensors`

![oma_single_trim](https://user-images.githubusercontent.com/13416487/86216624-9f3bef00-bb7e-11ea-9fd4-7723b0bdaddc.png)

For OMA with multiple measurements, the matrix `records` becomes 3-dimensional with the 3rd dimension representing each measurement. The reference sensors must always be the first columns in the matrix.

`size(records) = n_time, n_sensors, n_measurements`

![oma_multiple_trim](https://user-images.githubusercontent.com/13416487/86216634-a236df80-bb7e-11ea-8536-2248995bd00e.png)

The required format is described in more detail in the [pdf](https://github.com/KIT-FAST/modalAnalysis-OMA-EMA/blob/master/Implementierung%20des%20p-LSCF-Algorithmus%20zur%20Operational%20Modal%20Analysis.pdf) on page 46, unfortunately it is written in German.

I hope this helps. I'm going to ask the original author of this tool if he can add some example data.
