### ISSUE TITLE
Query regarding the use of OMA data in code

### ISSUE THREAD

**Issue by VinscentSun** [KIT-FAST/modalAnalysis-OMA-EMA#3]
I am writing to you to clarify a doubt regarding the use of EMA data in your code examples. I have noticed that in the code examples provided in your documentation, there is no mention of OMA data, and only EMA data is being used as an example.

As someone who is interested in working with both OMA and EMA data, I was hoping to find some guidance on how to work with both types of data. I understand that EMA data is easier to obtain and more widely available, but it would be helpful to have some guidance on working with OMA data as well.

I was wondering if you could shed some light on why the code examples do not include OMA data and whether you could point me in the right direction for resources on working with OMA data.

Thank you for your time and consideration, and I look forward to hearing back from you.

Best regards,
Linlin

**Comment by awiawi** [comment]
You can see #1 for a description about the required format of the input data. Hopefully we will improve the README of this repo at some time in the future and explain this there. :-)

Moreover, we will see if we can produce and add a sample file for OMA as it is already for EMA.

**Comment by awiawi** [comment]
The [Readme](https://github.com/KIT-FAST/modalAnalysis-OMA-EMA/blob/f2fac19dbbd0eb1b48550ed582af0c04202bb9ab/README.md) has been updated. Maybe this helps in using the software with OMA data.

**Comment by VinscentSun** [comment]
Thank you so much for your help and support. I will try my best to understand the required format of the input data for OMA.
