### ISSUE TITLE
why the damping ratio is always -1%

### ISSUE THREAD

**Issue by VinscentSun** [KIT-FAST/modalAnalysis-OMA-EMA#4]

**Comment by awiawi** [comment]
Can you please provide us with some more information? Do you mean the resulting damping ratios?

**Comment by VinscentSun** [comment]
> Can you please provide us with some more information? Do you mean the resulting damping ratios?

Thank you for your reply. Yes, I meant the resulting damping ratios. it seems that the resulting damping ratios are always [-1;-1;-1...]%, which is unusual since damping ratios should be positive values between 0 and 1. Based on this information, is it possible that there may be an issue with the way the damping ratios are being calculated or reported.

**Comment by awiawi** [comment]
You are correct, the damping ratios should be indeed positive by definition. Stable poles are identified by having a negative real part which means a positive damping ratio.

https://github.com/KIT-FAST/modalAnalysis-OMA-EMA/blob/7c830317472da969f26bd1c42d5c24743a74c186/modalAnalysis/modalAnalysis_pLSCF_main.m#L235-L246

The damping ratio later gets calculated by taking the negative real value (which should then be positive).

https://github.com/KIT-FAST/modalAnalysis-OMA-EMA/blob/7c830317472da969f26bd1c42d5c24743a74c186/modalAnalysis/modalAnalysis_pLSCF_main.m#L381-L382

Do you get these damping values with the example data provided? If you have not run the program with the example data and settings provided (meaning just run it right after a `git clone`), please do this first to confirm that the script runs as expected.

**Comment by VinscentSun** [comment]
Thank you so much for your help in resolving the issue with the damping ratios.  I truly appreciate your time and effort in assisting me, and I am grateful for your support.
